### ISSUE TITLE
Error on SD

### ISSUE THREAD

**Issue by ARX-7** [Immemor/RaidCore#10]
I think it has to do with wiping and then some of the calls / timers still go through while waiting for the next pull, not sure 100%

...unctionTool\Libs\GeminiTimer-1.0\GeminiTimer-1.0.lua:337: Gemini:Timer-1.0: CancelTimer(handle[, silent]): 'table: 00000001C4A82A80' - timer already cancelled or expired
stack trace:
    [C]: in function 'error'
    ...unctionTool\Libs\GeminiTimer-1.0\GeminiTimer-1.0.lua:337: in function 'CancelTimer'
    ...Roaming\NCSOFT\WildStar\Addons\RaidCore\RaidCore.lua:732: in function 'StopEmphasize'
    ...Roaming\NCSOFT\WildStar\Addons\RaidCore\RaidCore.lua:1096: in function 'ResetEmphasize'
    ...Roaming\NCSOFT\WildStar\Addons\RaidCore\RaidCore.lua:1225: in function <...Roaming\NCSOFT\WildStar\Addons\RaidCore\RaidCore.lua:1200>

...unctionTool\Libs\GeminiTimer-1.0\GeminiTimer-1.0.lua:337: Gemini:Timer-1.0: CancelTimer(handle[, silent]): 'table: 00000001C4A82A80' - timer already cancelled or expired
stack trace:
    [C]: in function 'error'
    ...unctionTool\Libs\GeminiTimer-1.0\GeminiTimer-1.0.lua:337: in function 'CancelTimer'
    ...Roaming\NCSOFT\WildStar\Addons\RaidCore\RaidCore.lua:732: in function 'StopEmphasize'
    ...Roaming\NCSOFT\WildStar\Addons\RaidCore\RaidCore.lua:1096: in function 'ResetEmphasize'
    ...Roaming\NCSOFT\WildStar\Addons\RaidCore\RaidCore.lua:1225: in function <...Roaming\NCSOFT\WildStar\Addons\RaidCore\RaidCore.lua:1200>

...unctionTool\Libs\GeminiTimer-1.0\GeminiTimer-1.0.lua:337: Gemini:Timer-1.0: CancelTimer(handle[, silent]): 'table: 00000001C4A82A80' - timer already cancelled or expired
stack trace:
    [C]: in function 'error'
    ...unctionTool\Libs\GeminiTimer-1.0\GeminiTimer-1.0.lua:337: in function 'CancelTimer'
    ...Roaming\NCSOFT\WildStar\Addons\RaidCore\RaidCore.lua:732: in function 'StopEmphasize'
    ...Roaming\NCSOFT\WildStar\Addons\RaidCore\RaidCore.lua:1096: in function 'ResetEmphasize'
    ...Roaming\NCSOFT\WildStar\Addons\RaidCore\RaidCore.lua:1225: in function <...Roaming\NCSOFT\WildStar\Addons\RaidCore\RaidCore.lua:1200>

...unctionTool\Libs\GeminiTimer-1.0\GeminiTimer-1.0.lua:337: Gemini:Timer-1.0: CancelTimer(handle[, silent]): 'table: 00000001C4A82A80' - timer already cancelled or expired
stack trace:
    [C]: in function 'error'
    ...unctionTool\Libs\GeminiTimer-1.0\GeminiTimer-1.0.lua:337: in function 'CancelTimer'
    ...Roaming\NCSOFT\WildStar\Addons\RaidCore\RaidCore.lua:732: in function 'StopEmphasize'
    ...Roaming\NCSOFT\WildStar\Addons\RaidCore\RaidCore.lua:1096: in function 'ResetEmphasize'
    ...Roaming\NCSOFT\WildStar\Addons\RaidCore\RaidCore.lua:1225: in function <...Roaming\NCSOFT\WildStar\Addons\RaidCore\RaidCore.lua:1200>

**Comment by NielsH** [comment]
This is an error I've never seen before. Does it occur on certain bosses? 

I see the GeminiTimer you're using is from http://www.curse.com/ws-addons/wildstar/221305-protostar-multifunction-tool - perhaps the code is different. Could you try with that addon disabled?

**Comment by ARX-7** [comment]
We are still progressing on SD so its happened once or twice on them.  i have disabled protostar multifunction tool, will report back it it happens again.

**Comment by NielsH** [comment]
Hey,

Has this been an issue since disabling the other addon? Otherwise will close this :+1:

**Comment by ARX-7** [comment]
Had another night on daemons, no issues with the other add on disabled
