### ISSUE TITLE
Add option to decline summons

### ISSUE THREAD

**Issue by NielsH** [Immemor/RaidCore#100]
Currently, Raid leaders and assistants can use /raidc summon to force people to accept any pending summons.

However, even though only raid leaders and assistants can use it, there are still some among those that abuse it. So people have asked me to add an option to disable it.

Such an option can be seen in pull request #99 

It was mentioned to add this in 2.0, and not 1.x - though I would personally prefer to have it in 1.x. It's not a big change and it will ease some frustrations when raid leaders/assistants are in a trolling mood ^^

**Comment by Immemor** [comment]
hum... I will propose you a new milestone.

A v2.0 for the monday night (before id reset). In this v2, we will add following issues :
- #100,
- first implementation of #91,
- and the pull request #95.

Every other issues will be delay for a v3.

**Comment by NielsH** [comment]
OK for me, I might have a look on PTR to see if I can reproduce/fix #90 but if not let's stick to that indeed for monday.
