### ISSUE TITLE
Limbo Infomatrix  & Desert Swarm.

### ISSUE THREAD

**Issue by Immemor** [Immemor/RaidCore#116]
Request from  Mr_KidSam's on Curse.

Would it be possible to add some kind of marker to identify the path for the bees(Desert Swarm) on Limbo Infomatrix? This would be greatly appreciated.

**Comment by adamjedlicka** [comment]
Yes it's possible. We were tracking it with tracktor. There's a unit in the middle of the circle, so just drew two circles with the same diameter as desert swarm (8-15units)
Name of the unit: 16623 Hostile Invisible Unit for Fields (0 hit radius) (Very Fast Move Updates) - BEAX
