### ISSUE TITLE
Custom bar colors in new version is bugged (?)

### ISSUE THREAD

**Issue by adamjedlicka** [Immemor/RaidCore#118]
I tired messing with bar colors in new version in Y83 and found it impossible. I tired this:

``` lua
mod:AddTimerBar("NEXT_IRRADIATE", "~Next irradiate", 27, true, { sColor = "FF00FF00" })
```

and bar color was still slightly red. When I tried printing color code in BarManager (tOptions.sColor) it was that red even thou I haven't found this color to be declared anywhere.

**Comment by adamjedlicka** [comment]
Found the problem in my code, closing issue.

**Comment by Immemor** [comment]
oki ^^

**Comment by Immemor** [comment]
About Y83, I have a branch to test. This branch is available in the git.

**Comment by adamjedlicka** [comment]
Yeah I know about it. I forked it for testing purpouses.
