### ISSUE TITLE
Event RAID_WIPE is not fired

### ISSUE THREAD

**Issue by ghost** [Immemor/RaidCore#119]
When doing Y83, the function "OnReset()" is never called. I never get the event RAID_WIPE.

I will test for other encounter tonight.

**Comment by Immemor** [comment]
?? There is not function 'OnReset' in this boss, and the event is not registered.

In fact, there no need of this function everywhere, I will probably rework that (later).

**Comment by Immemor** [comment]
Can I close this issue ? As I answer by wisp in game.
