### ISSUE TITLE
How to properly use DEBUFF_APPLIED event?

### ISSUE THREAD

**Issue by adamjedlicka** [Immemor/RaidCore#120]
I'm trying some stuff for augmentors and for some reason I'm unable to make DEBUFF_APPLIED and DEBUFF_REMOVED work. It doesn't proc my function at all. Is it possible I'm doing something wrong or is it bugged?

EDIT: Even in Y83 branch it isn't working on augmentors.

**Comment by Immemor** [comment]
With the current implementation: UnitBuff() or UnitDebuff() must called to set the filter.
Otherwise events are not raised to the encounter.

**Comment by adamjedlicka** [comment]
Isn't this a little bit inconvenient? With this I have to mark everyone in the party if I want to watch them.

**Comment by Immemor** [comment]
Yes, it is.

But, my priorities are:
1. Data saved structure to simplified, and improve for next feature.
2. Draw manager to rebuild (marker, line, etc...) => to reduce cpu mainly.

**Comment by NielsH** [comment]
You can use RaidBuff() and RaidDebuff() to watch everyone in the party iirc

**Comment by adamjedlicka** [comment]
Oh cool thanks

**Comment by NielsH** [comment]
API 10 actually introduced new event handlers for buffs / debuffs. Using that would probably be cool for the future, and it should also increase performance since there's no more need to do polling on units for buffs/debuffs

iirc the data table that is returned is the same is GetBuffs() currently has.

**Comment by Immemor** [comment]
Interesting, where did you get this information ? wildstar's forum ?

**Comment by Immemor** [comment]
Ok, I see it.

**Comment by adamjedlicka** [comment]
@NielsH if you mean events BuffAdded, BuffUpdated and BuffRemoved then they are bound to UI element called 'BuffContainerWindow' (basically buff/debuff frame on unit frames). I don't know if you can somehow manipulate it to apply those events to all units.

**Comment by NielsH** [comment]
I haven't tried them, I just saw the API notes:
New Events: BuffAdded, BuffRemoved, BuffUpdated. These events provide a
unit object and a table containing information for an individual buff, in
the same format as the existing GetBuffs() API call.

**Comment by Immemor** [comment]
I will try, but I'm not sure that better. Because we will have many many interruptions, 1 by unit and buff.

And the polling become a better implementation when interruptions are too high.

**Comment by Immemor** [comment]
Behavior changed, no more filtering.

Player's Debuff are always raised to encounter
Foes's Buff request only the `WatchUnit()` function registering.

WatchUnit will enable processing for Cast and Buff.
