### ISSUE TITLE
Rework DrawManager

### ISSUE THREAD

**Issue by Immemor** [Immemor/RaidCore#126]
Rework this last to bring more feature support and less cpu load too.

**Comment by Immemor** [comment]
My first result are unbelievable.

![RaidCore Graph](http://img11.hostingpics.net/pics/554950RaidCoreGraph.png)

Before this commit:
- There a CPU leak, because the NextFrame is registered many times !!!
- The cost of creation/destruction of windows object is really high !!

**Comment by NielsH** [comment]
I still follow this a bit, just wanna say really awesome job with these
improvements!! Very happy you're taking care of the project and that you're
doing such a great job at it. Keep up the good work :)

**Comment by Immemor** [comment]
4.0-alpha out.
