### ISSUE TITLE
Feature Request: Pull Countdown timer

### ISSUE THREAD

**Issue by Vass1979** [Immemor/RaidCore#128]
It would be really nice for raid leaders if they could type something like /pull 5 and have raidcore initiate a countdown visible to all for an incoming pull, maybe using the same voice used for system deamons control group down, 5....4....3....2....1 PULL!

Would help greatly

**Comment by NielsH** [comment]
This is already possible with /raidc pull 5 for example. Though I'm not
sure how well it syncs at this point, I believe there were some issues with
syncing it between all party members since they changed ICCommLib with the
last drop .. But you can try it out that way at least

**Comment by Vass1979** [comment]
Ah ok, the functionality is there, but it's not working properly.

The countdown timer counts, but when it reaches 0 the message remains there. Also it seems that if the one initiating the pull timer is moving or sprinting, the countdown stops, no idea why.

**Comment by Immemor** [comment]
Hum, I will ask 1 thing. Did you use the release version under curse which is  "2.0" or did you configure curse to accept alpha version ? and so you have the "3.2-alpha".

I need this information, because I rebuild totally the bar services on 3.0.

**Comment by Vass1979** [comment]
I use the release version on curse, should I use the alpha version?

**Comment by Immemor** [comment]
In the last alpha, the #125 is a bug which I have introduced. But I fix many many things, and introduce some features.

For me you have no risk. After, If currently you disable some part of raid core then you should wait a little bit.

**Comment by Immemor** [comment]
I close this issue, as the 3.x release is available on curse.

If you have any trouble don't hesitate to reopen this issue.
