### ISSUE TITLE
Updates on Curse.com

### ISSUE THREAD

**Issue by LynxyssCZ** [Immemor/RaidCore#138]
I noticed, that curse tells you that the Raidcore addon gets updated. It is still stuck at 2.0.
Are there any plans on pushing a real new version onto the Curse?

**Comment by Immemor** [comment]
It's true, the last release is 2.0 and the last Alpha is 3.6.

I will do a official release very soon, in same time as the small newspaper on Solaris Guild.
More exactly in 1 weeks approximately.

**Comment by Immemor** [comment]
3.8-alpha will be the candidate, I plan to do a release on sunday.

**Comment by LynxyssCZ** [comment]
Oh, thanks for your great work.
We converted most of our guild to updating directly from git, but more frequent releases to the curse would make a lot of things much easier.

**Comment by Immemor** [comment]
Well it's not useful, alpha, beta or release are delivered to Curse too.

You just need to select your preferred delivery on Curse client:

See: http://www.hostingpics.net/viewer.php?id=147747Curse.png

**Comment by LynxyssCZ** [comment]
And what about people not using curse client, but downloading .zip fron
curse?

**Comment by Immemor** [comment]
Did you have access to:

http://wildstar.curseforge.com/ws-addons/227908-raidcore/files

**Comment by Immemor** [comment]
Zip are available here also: https://github.com/NielsH/RaidCore/releases

**Comment by Immemor** [comment]
Release 3.10 send to curse 2 days ago.
