### ISSUE TITLE
Experiment X-89 issue with little bomb

### ISSUE THREAD

**Issue by ghost** [Immemor/RaidCore#139]
When the debuff gets applied to a player I get the warning and countdown for every bomb in the raid not only the ones I am affected by. Seeing the code there is no check whether the player itself is the target:

```
function mod:OnDebuffApplied(unitName, splId, unit)
    if splId == 47316 then
        core:AddMsg("LITTLEB", self.L["LITTLE BOMB on YOU !!!"], 5, "RunAway", "Blue")
        core:AddBar("LITTLEB", self.L["LITTLE BOMB"], 5, 1)
    end
end
```

**Comment by Immemor** [comment]
Hi,

Kina have started to fix with https://github.com/NielsH/RaidCore/pull/132 , but he don't give any sign of life since 2 or 3 weeks.

So I will fix his branch, no real choice.
