### ISSUE TITLE
Missing French translations for GA bosses

### ISSUE THREAD

**Issue by olbat** [Immemor/RaidCore#140]
Hi,

It seems that the Kuralak helper does not work anymore on the French client.

The addon does not even start so I think that it's a problem with the event that identifies the start of the fight.

Thank you for this wonderful addon !

**Comment by olbat** [comment]
Ok, just saw that some traductions are missing, so it never worked at all, nevermind :)

**Comment by olbat** [comment]
If I add the missing translations Tuesday evening, do you think that it will be possible to include them in the 3.8 release ?

**Comment by Immemor** [comment]
I can do a 3.9-alpha. And I should try to find à GA as a PU. Because my guild don't do it since few months. So, it's difficult for me to check.

**Comment by olbat** [comment]
I'll do it this week with my team, I'll try to find someone in my guild to test the modifications before I push the PR (I do not have the French client).

If needed, I may also be able to give you access to the corresponding /rclog :)

**Comment by Immemor** [comment]
To understand what happen in a combat, I more efficient with log provided by RaidCore and video.
Could you broadcast on twitch ?

**Comment by Immemor** [comment]
take the last version (3.8-alpha), with 3.7-alpha you will have some troubles.

**Comment by olbat** [comment]
Sadly, I doubt that any member of my guild can/want to Twitch our fights :(

We one-tried the boss so I only have one log file: https://gist.github.com/olbat/5c31432b381fa63df915.
If needed, I will add more logs next week (next time we'll fight it).

I've made a PR (#141) with most of the missing translations. Translations for 3 NPCSay messages are still missing, I can't locate them in the logs (probably because the boss did not used them during this fight).

For the moment I'll try to add missing French translation for the other bosses.
Since less are missing (4 for Prototypes, 2 for Phage Maw, 1 for Council), I think it will be easier.

**Comment by olbat** [comment]
If it can help, here are the translations of Kuralak's spells:
- [Kuralak la Profanatrice](http://wildstar.datminer.com/fr/npc/52969) / [Kuralak the Defiler](http://wildstar.datminer.com/en/npc/52969)
- [Disparaître dans les ténèbres](http://wildstar.datminer.com/fr/spell/60121) / [Vanish into Darkness](http://wildstar.datminer.com/en/spell/60121)
- [Corruption chromosomique](http://wildstar.datminer.com/fr/spell/56652) / [Chromosome Corruption](http://wildstar.datminer.com/en/spell/56652)
- [Nourrir la corruption](http://wildstar.datminer.com/fr/spell/60559) / [Cultivate Corruption](http://wildstar.datminer.com/en/spell/60559)
- [Répulsion](http://wildstar.datminer.com/fr/spell/57729) / [Vileness](http://wildstar.datminer.com/en/spell/57729)
- [Invasion](http://wildstar.datminer.com/fr/spell/60623) / [Outbreak](http://wildstar.datminer.com/en/spell/60623)
- [Siphon d'ADN](http://wildstar.datminer.com/fr/spell/56589) / [DNA Siphon](http://wildstar.datminer.com/en/spell/56589)
- [Vue obstruée](http://wildstar.datminer.com/fr/spell/51605) / [Obstruct Vision](http://wildstar.datminer.com/en/spell/51605)

**Comment by Immemor** [comment]
Hum, Obviously you haven't used the alpha version. Because I can see player's pets, And I removed them from lower interface from 3.1-alpha. A long time ago so.

Did you used the Alpha of RaidCore ?

**Comment by olbat** [comment]
I suppose that the person that launched the addon with the French client (not me) used the version that's available on Curse, so the last non-alpha/beta release ...

Does the alpha version add some debug information ?

**Comment by olbat** [comment]
I've updated the Kuralak's PR (#141) using new logs (the gist has been updated).

I've also made a PR for Prototypes (#142), here are the logs: https://gist.github.com/olbat/1fc89e9ca7804a5f59ad.

**Comment by Immemor** [comment]
Well, all your translations seems goods, but you have forgotten the comma on end of line.
It's an array, item must be separated by a comma.

**Comment by olbat** [comment]
Oops, my bad, I've just fixed it :)

Edit: seems to be too late, thank you to have fixed this for me.

**Comment by olbat** [comment]
So, to sum up, translations that are still missing (GA): 2 messages for Kuralak and 2 for Phage Maw.
