### ISSUE TITLE
Encounters/GA: players that have the eggs debuff are no longer marked on Kuralak

### ISSUE THREAD

**Issue by olbat** [Immemor/RaidCore#145]
It seems that since the 3.7-alpha release, on GA/Kuralak,  players that have the eggs debuff are no longer marked (the mark with the numbers).

From what I can see in [the diff](https://github.com/NielsH/RaidCore/compare/2.0...3.7-alpha#diff-14b1ce396c8e268e5e5f01f90d6b18a7R219), the update of the `mod:OnDebuffApplied` function seems to be bugged :)

**Comment by Immemor** [comment]
The function name is wrong, and arguments are corrects:

``` lua
Apollo.RegisterEventHandler("DEBUFF_ADD", "OnDebuffAdd", self)

function mod:OnDebuffApplied(nId, nSpellId, nStack, fTimeRemaining)
   ...
end
```

**Comment by olbat** [comment]
I've made the change, prefered `OnDebuffAdd` since it seems to also be used in other bosses.

**Comment by Immemor** [comment]
It did the commit ^^ on my side.
