### ISSUE TITLE
German translation: System Daemons + question

### ISSUE THREAD

**Issue by Eikju** [Immemor/RaidCore#16]
Heyho :D

I translated "System Daemons" into German with Multi-Language-Support. French could be also easy to include because of locale strings. Here is the whole File: https://gist.github.com/Eikju/e9c63a61cc8c8a8894f4

And here is my question. I also mentioned that there is some "print text" at the end of the boss module like ...

```
if num > nbKick then 
    Print(msgStrings[locale]["numberPrint"])
    return
end
if position:lower() == "north" then
    intNorth = num
    Print((msgStrings[locale]["positionNPrint"]):format(num))
elseif position:lower() == "south" then
    intSouth = num
    Print((msgStrings[locale]["positionSPrint"]):format(num))
else 
    Print((msgStrings[locale]["positionBadPrint"]):format(position))
end
```

Can you tell me when it will be activated? Right now I do not understand it :)

**Comment by NielsH** [comment]
It's a way to set interrupter rotations... I /believe/ it is /raidc sysdm north 1 to indicate you're the first interrupter. 

It was used fairly early in DS fights, but I don't think anyone uses that function now (I have no idea if it even works)

**Comment by Eikju** [comment]
aaah, okay. Seems interesting :D. Thx for the information.

**Comment by NielsH** [comment]
Cool, good luck translating! :)
