### ISSUE TITLE
Transferring ownership

### ISSUE THREAD

**Issue by NielsH** [Immemor/RaidCore#162]
Hello!

It's very good to see the project is having good progress and development. Thanks for maintaining all of this!

I think now is a good time to transfer ownership to @Immemor - unless of course you think otherwise?

Please let me know your thoughts regarding this

Cheers,
Kami/Niels

**Comment by Immemor** [comment]
^^, I accept the mission.

If you transfer it for github and curse, I could have the possibility to add another guy, one day ... :)

**Comment by NielsH** [comment]
I just transferred the ownership for Curse and Github. I was in the Curse Rewards Program, a while ago (shortly you took over) I changed the reward split to 100% you, so make sure to check that out. Rewards are very minimal, but hey, it's something :+1:  (about $100 per 100K downloads I believe)

I might pop on in-game some time when it becomes F2P, I probably won't do much addon-wise but I'll definitely use Raidcore when I do try out Wildstar again. Looking forward to your changes!
