### ISSUE TITLE
Problem with System Daemons / Wave 2 buggy

### ISSUE THREAD

**Issue by Eikju** [Immemor/RaidCore#31]
Hey there :)

Yesterday we tried System Dameons and I recognized that wave 2 wouldn't count. Wave 1 works perfectly but after that wave 2 = miniboss, wave 3 (miniboss) = wave 4, wave 4 = miniboss and so on.

There seems to be something wrong.

**Comment by NielsH** [comment]
Are you sure you're using the latest git version? I fixed this earlier https://github.com/NielsH/RaidCore/commit/aaef6ac80f80fa8a415969eefbc53c2723b707f4

**Comment by Eikju** [comment]
I use this one: https://github.com/NielsH/RaidCore/blob/translation2/Modules/SystemDeamons.lua

Seems that the translation branch is outdated. I will fix that in in my version right now. Thx for help :)

**Comment by NielsH** [comment]
"Really old" is actually just a few commits behind. Anyways, assuming this is fixed then. let me know if there are issues with the latest version.
