### ISSUE TITLE
replace buff identification string by spellId.

### ISSUE THREAD

**Issue by Immemor** [Immemor/RaidCore#35]
There are some translations which can be avoided.

In **SystemDaemon**:

``` lua
function mod:OnDebuffRemoved(unitName, splId, unit)
    local eventTime = GameLib.GetGameTime()
    local tSpell = GameLib.GetSpell(splId)
    local strSpellName = tSpell:GetName()
    if strSpellName == "Overload" then
        core:DropMark(unit:GetId())
    elseif strSpellName == "Purge" then
        core:DropMark(unit:GetId())
    end
end
```

All debuff/buff should work with the spellId, it's faster and that don't request any translation.
For the previous code citation, 2 constants should be declared. That should give:

``` lua
local DEBUFFID_OVERLOAD = 1234
local DEBUFFID_PURGE = 2345

function mod:OnDebuffRemoved(unitName, splId, unit)
    if splId == BUFFID_OVERLOAD then
        core:DropMark(unit:GetId())
    elseif splId == BUFFID_PURGE then
        core:DropMark(unit:GetId())
    end
end
```

I will not do it with the translation job, I prefer split task. Because ID are needed to do it.

Note: There is maybe, some other boss like that. It's why a create this ticket also.

**Comment by NielsH** [comment]
This is true, and it has already been done with Spell IDs in some locations, but for easier creation of modules some have been done with the actual strings, however they can indeed be replaced now.

Getting the spell ids is something that has to be done during the actual raid/boss fight, so I'll see what I can get next reset and change it around.

**Comment by Immemor** [comment]
As log system have been pushed in master, it's easier to record a combat and this ticket could be done easier so.

**Comment by Immemor** [comment]
For the v3.0, don't forget to catch a partial log. I just started to try this encounter. I haven't your progress to do it.

**Comment by NielsH** [comment]
https://docs.google.com/spreadsheets/d/1oPCcvAe_yOmmwGd-fvt6mQHqjhgbZ0RPyV4eVz36PQs/edit?usp=sharing

Avatus full fight, yellow room and blue room

**Comment by Immemor** [comment]
Hum, 833 seconds , you click only once time on the button 'Copy to clipboard' ?

**Comment by NielsH** [comment]
We just kill so fast ^^

I had to click 3 times, if you check the last part of the log you can see
it includes the loot that is being spawned as Avatus dies, so it is a
complete log :)

**Comment by Immemor** [comment]
Ok, I expected more 20 min. I was surprised.

**Comment by Immemor** [comment]
Arf,I really love Carbine....

| Time | SpellName (Event BuffAdd) | SpellId |
| --- | --- | --- |
| 519.006s | "Red Empowerment Matrix" | 44859 |
| 539.307s | "Red Empowerment Matrix" | 44859 |
| 559.701s | "Red Empowerment Matrix" | 44947 |
| 580.205s | "Red Empowerment Matrix" | 44859 |
| 598.017s | "Red Empowerment Matrix" | 44949 |
| 600.412s | "Red Empowerment Matrix" | 44947 |
| 619.531s | "Red Empowerment Matrix" | 44949 |

3 Identifiers just for 'Red Empowerment Matrix' : 44949, 44947, 44859

**Comment by Immemor** [comment]
https://docs.google.com/spreadsheets/d/1D62Xc3D3mJACABlO2A4TonR8nFhfMXMvpg50jK5f3Fg/edit#gid=346400825

with filter added.

**Comment by Immemor** [comment]
Most or all boss have been done.
