### ISSUE TITLE
Translate the few entries about ZoneName

### ISSUE THREAD

**Issue by Immemor** [Immemor/RaidCore#46]
olbat, Could u look if you can translate few more entries.

I provided you a branch (which I will review), which is https://github.com/NielsH/RaidCore/compare/encounter_registering

It's the last step for French and German support.

The reference file is Locale/enUS.lua.

File to fill is Locale/frFR.lua and Locale/deDE.lu

Thank

**Comment by olbat** [comment]
Hi,
Unfortunately, [the website](http://wildstar.datminer.com/) I'm using to gather the translation does not reference zones the same way it references items (you can't find zones from the research bar).

I found a workaround but it will take some time to adapt the script, I'll keep you aware of it :)

**Comment by olbat** [comment]
Done: #49 

**Instructions**

```
$ cp Raidcore/Locales/enEN.lua cp Raidcore/Locales/frFR.lua
$ docker run -v $(pwd):/src/ olbat/ws-raidcore-translator \
    raidcore-translator i18n_v3 -v -l fr /src/Raidcore/Locales/frFR.lua

$ cp Raidcore/Locales/enEN.lua cp Raidcore/Locales/deDE.lua
$ docker run -v $(pwd):/src/ olbat/ws-raidcore-translator \
    raidcore-translator i18n_v3 -v -l de /src/Raidcore/Locales/deDE.lua
```
