### ISSUE TITLE
Fill empty entries language for french and german

### ISSUE THREAD

**Issue by Immemor** [Immemor/RaidCore#47]
After the huge work done with https://github.com/NielsH/RaidCore/pull/38, there still some entries to write.

To be done for May delivery.

**Comment by olbat** [comment]
I would like to help on this but I play with the English client.

Most people of my guild are playing using the French one so I can ask them some help on this.

They may need some instructions to know where/when to look for Spells/NPC names to translate.
If I understood, you added a debug mode ? I think it'll be useful in this case :)
If yes, is there some instructions somewhere to explain how to use it ?

**Comment by Immemor** [comment]
I did it with DruseraBossMods Addon, Every event from the game, every decision take on the core are logged in a memory.
And that record, only if the player is in combat, or in group.

If the user want to see it, he have to click on Encounter's log.

But it's on My version of boss mod.
Sometimes I'm hesitating, continue RaidCore, or just finish DruseraBossMods.
Because I took 100k of memory against 700k today with RaidCore.
And for sure, I take less cpu.

**Comment by olbat** [comment]
Isn't there some optimizations possible for RaidCore (is it possible to [profile](http://en.wikipedia.org/wiki/Profiling_%28computer_programming%29) LUA scripts ?) ?

**Comment by olbat** [comment]
**Note for translators**: here is a list (`filename`,`line#`) of names that have not yet been translated : [French](https://gist.github.com/olbat/0be6b294d689d410e3d6#file-french), [German](https://gist.github.com/olbat/0be6b294d689d410e3d6#file-german).

**Comment by Immemor** [comment]
- **GeminiProfiler** is for Carbine function only. Not for addon, from what I try two month ago.
- **GeminiLogging** is fun... but useless. Take much more cpu and memory than simple array.
- **AddonsMonitor** ... I don't remember it. It's maybe usable
- **GeminiTimer**, it's a big shit. take a lot of cpu and memory. And that use some deprecated event like VarChange.
- **LibBusted** , test functions are really limited.
- **GeminiAddon**, It's fun... but that doesn't bring anything as feature. A simple metatable can do the same.

**Comment by olbat** [comment]
Do we really care about the memory/CPU/... consumption of the profiling tool ?
I mean, it will only be launched by developers during development, right ?

**Comment by olbat** [comment]
I've tried to look at them really quickly, the only one that seems to be interesting for our problem is **GeminiProfiler** but sadly it does not provide any information about memory consumption :(

**Comment by Immemor** [comment]
addonMonitor is funny, but measures done in **ms** are maybe underestimate.

Just for information the cpu load taken by RaidCore, is really high.
See the measure done with a french client on Gloomclaw: http://hpics.li/e196dc6

I was comparing my DruseraBossMods and RaidCore.
I think, that should be worst with an English client.

**Comment by Immemor** [comment]
2 ms take per frame. On the screenshoot I was a 40 fps. So 1 frame is equal to 0.025 ms.

In others words, 2 / 25 is 8% here. As we can see, sometime peak on cpuload are really high. In other words, RaidCore do some freeze.

**Comment by olbat** [comment]
Okay, so there is some optimization work to do apparently :) Did you take a look on the code ?

**Comment by Immemor** [comment]
Yep, I already started some tasks, like:
- Added my logger in low layer : DONE
- Add a first low layer robust and fast : DONE
- Add a Graphic User Interface to read log: 80% DONE
- Link this first layer with RaidCore: 30% DONE

The next steps are:
- Remove all zone code. because it's useless.
- Rebuild timer management, It's take to much CPU.
- Remove GeminiAddon on bosses, and use a metatable. (memory reduction, and small cpu improvement)

**Comment by Immemor** [comment]
I tested Current head of RaidCore in french, is it not working in english ? because we have some late for this month.

I planned to push my huge modification for the next delivery, next month so.

**Comment by NielsH** [comment]
English master is currently broken yes, I can look at it this evening at
least, the issue seems to be that some calls to the bossprototype don't
work, I checked with rover and it doesn't even see the existence of some
functions

On phone now so bit short response :)

**Comment by Immemor** [comment]
hum, maybe we can detect them quickly with something like:

``` lua
mt = {}

function mt:__index(k)
  Print(("Missing entry for '%s'"):format(k))
  return function() assert(true) end
end

EncounterProtototype = setmetatable({}, mt)
```

**Comment by olbat** [comment]
I was thinking about having two kind of messages:
- _Error_ ones when an important translation is missing (the addon cannot work without it): NPC/Spell/Zones names and datachron messages
- _Warning_ ones for UI messages

That would helpful for translators to know what to focus on without having to look at the code + know when to stop looking at the logs and translate "manually".

What do you think about it ?

_...I know that it will take some time to make this modifications but I'm sure it will be useful for translating tasks now and for the future content._

**Implementation**
One problem to do that is that those two kind of information are mixed in the translation array.
I can separate them if needed but I need to know how (create another translation array for UI messages, prefix UI messages key in the translation array, ...).

Eventually, since there is some separation in the code for NPC/Spell/Datachron names we should separate this things too ?
(Like this we would be able to display an error such as "_Error: the add-on was unable to translate the ... spell name_" so translators would know what to look for).

**Comment by Immemor** [comment]
Did u try, just to disable the "Silent" mode in GeminiLocale.

Because all your request is done by him for me.

**Comment by olbat** [comment]
I have the English client, so I think that it will not help a lot :)

GeminiLocale diplays if the missing locale describe a custom UI message, a Spell or an NPC name, ... ?

**Comment by Immemor** [comment]
This last will print, where the Key is missing : Boss + Keyname.

The message is printed only once by runtime.

An error in another language cannot be detected. You must run in this targeted language to catch the missing translation. And I'm think, it's acceptable.

PS: You have to probably disable the default language too.

**Comment by olbat** [comment]
Okay, so you have to look in the code to know what to look for in the game. That was what my solution was allowing to avoid (translation task can be done by non-developers this way).

Your method seems convinient too, I'll try configure GeminiLocale as you advice, thanks :)

**Comment by Immemor** [comment]
Well, Your parsing is good the first time. After that must be completed when the boss is written.

**Comment by Immemor** [comment]
I will test that, tonight.

https://github.com/Immemor/RaidCore/tree/logger

First implementation of logs are in:  /rclog

I would like to delete all the code in OnUnitCreated@RaidCore.lua. I simply trig on raid in combat / out combat.

**Comment by Immemor** [comment]
global issue is no more needed.
