### ISSUE TITLE
Ep Water/Air feedback

### ISSUE THREAD

**Issue by Immemor** [Immemor/RaidCore#51]
I tried this encounter yesterday, with a French and an English game version.

Well, I was surprised.
- There not a lot of thing on this boss. 2 timers... which seem useless and wrong. 
  The timer about player in ice is wrong, and more or less useless too.
- In the EpAirWater.lua file, there is some action on datachron message.... There is no datachron message during the encounter... Is it a copy/paste from another boss ?

On this boss, the minimum is:
- The timer on next P2, when hydroflux will move to the center of the room.

**Comment by NielsH** [comment]
Water/Air actually has quite a bit looking at the code, see: https://github.com/NielsH/RaidCore/blob/master/Modules/EpAirWater.lua

For example, search for `midphase` and you'll see it's there, as well as Twirl warnings , Icestorm and frost tomb warnings . I'm pretty sure there are datachron messages as well, though not 100%, I'll have to check next time we do that boss.

Frost tomb timer is an estimate, I couldn't find an exact trigger (but the estimate is indicated by the ~ in front of the timer). For us it was fairly useful at least. This is also true for some midphases, but I believe they are more accurate than the ice tomb ones. I believe he has to finish his cast sometimes which will cause it to be a few seconds off.

**Comment by Immemor** [comment]
I still don't see any datachron messages on this encounter, at least until 33% of their health.
And the same on this video: https://www.youtube.com/watch?v=ww_ynwpssFw

**Comment by NielsH** [comment]
Hmm.... It's probably some old 40M code then.. Looking at https://www.youtube.com/watch?v=vAQfPbdKHGI for example, I see the Datachron messages there... I suppose it can indeed be removed if that is the case yes.

**Comment by Immemor** [comment]
^^
