### ISSUE TITLE
Health tracked on unit

### ISSUE THREAD

**Issue by Immemor** [Immemor/RaidCore#52]
I'm terribly disturb with RaidCore, about the current implementation of health bar on screen.

On DruseraBossMods, I added the a cast bar. And so, it's like to have a automatic focus.

So, for me RaidCore should:
- Add the cast bar.
- Add the absorb bar if exist
- Add the shield bar if exist

And for the the design of ForgeUI, could be great.

**Comment by NielsH** [comment]
I actually quite like the Minimalist sprite. There's the option to change colors, which will allow you to somewhat tweak the look/feel of it.

If that's not enough, we could add different sprites (I guess Forge just uses a flat white one?) and have the option for people to choose which sprite to use. For me, I'd like to keep the current one at least as I do like it.

I see you did it like this: http://media-curse.cursecdn.com/attachments/140/682/d7e344fc215270333d71e8f5f496c5e4.jpg  
which is pretty cool, I think it'd be a great addition.

Perhaps we'll have to decide after the next release a list of enhancements to make and the priority of them, so we can establish a general direction of things to do and change in the addon.

**Comment by Immemor** [comment]
sure ^^
