### ISSUE TITLE
bug with self.wipeTimer

### ISSUE THREAD

**Issue by Immemor** [Immemor/RaidCore#59]
Bug with a trash mob which have reset.

```
...Roaming\NCSOFT\WildStar\Addons\RaidCore\RaidCore.lua:1410: attempt to index field 'wipeTimer' (a nil value)
stack trace:
    ...Roaming\NCSOFT\WildStar\Addons\RaidCore\RaidCore.lua:1410: in function <...Roaming\NCSOFT\WildStar\Addons\RaidCore\RaidCore.lua:1400>
```

``` lua
function RaidCore:WipeCheck()
    for i = 1, GroupLib.GetMemberCount() do
        local unit = GroupLib.GetUnitForGroupMember(i)
        if unit then
            if unit:IsInCombat() then
                return
            end
        end
    end
    Print("WIPE")
    self.wipeTimer:Stop()
```

self.wipeTimer doesn't exist.

**Comment by NielsH** [comment]
Hm, this is kinda weird, since WipeCheck() is actually called via ApolloTimer on self.wipeTimer itself:
https://github.com/NielsH/RaidCore/blob/master/RaidCore.lua#L1540

If self.wipeTimer == nil then WipeCheck shouldn't even be triggered,

**Comment by Immemor** [comment]
Well, I not agree with your proposal.
I fact, I don't see the interest to delete the timer object. This last can be keep in stop state.

**Comment by NielsH** [comment]
Well, it's not really a proposal, that's just the way it is right now, so I'm just saying it's weird it gives the lua error when it shouldn't happen.

AFAIK ApolloTimer doesn't have an IsRunning() function though, so it'll be tricky determining if it is in the started/stopped state without something similar to what self.wipeTimer is currently doing with setting it to nil.

Though self.wipeTimer is only started here: https://github.com/NielsH/RaidCore/blob/master/RaidCore.lua#L1538 - I'm not sure if it can hurt just getting rid of the check and only using Start/Stop()
