### ISSUE TITLE
bug: Ohmna

### ISSUE THREAD

**Issue by Immemor** [Immemor/RaidCore#68]
This ticket is related to Ohmna only, but the history is in https://github.com/NielsH/RaidCore/issues/43.

To sum up:  
- Ohmna shows the first pillar assignment, but it doesn't show you all the next pillars at all
- This bug was seen before the push of the 'log system', that could fix the problem.

**Comment by NielsH** [comment]
https://github.com/NielsH/RaidCore/blob/master/Encounters/GA/Ohmna.lua#L195

Should be upper-case?

**Comment by Immemor** [comment]
Yes, but that doesn't explain why the english doesn't work.

It's why I prefer to set GeminiLocal with warning enable.

**Comment by NielsH** [comment]
Well of course it can be enabled - just not in the version we release to Curse. 

Does GeminiLocale cleanly warn about calls to nonexistant-array keys? I thought it would only do it if it was present in the "primary" language but not in the translated one.

**Comment by Immemor** [comment]
If you open the GeminiLocale, the silent mode equal to true remove only the print to user if the key don't exist.

After that, the library will create the entry and set as value the key itself. So the warning is print only once by session.

I think, It's a good thing to do in curse release, because users can help to detect entries which are not set.
Like that, you can quickly converge to a good languages support.

Or we can activate it in alpha mode.

**Comment by NielsH** [comment]
Would it not be possible to make it a config toggle in the UI? We can default it to on, but people that don't want it can disable it then

**Comment by Immemor** [comment]
I most simple is to manage that with alpha or release tag. Add one more option, will add complexity. And it's useless for 90% of the users.

**Comment by NielsH** [comment]
I'm fine with it either way, but I think very few users on Curse actually select the beta/alpha channel. But if you think it makes things easier, I am fine with it.

**Comment by Immemor** [comment]
Well, I have in mind to select few users. With this few users, we can ask them to select alpha or beta version on curse.

More exactly this few users will be near us. In our guild by example. ^^
