### ISSUE TITLE
Check System Daemon

### ISSUE THREAD

**Issue by Immemor** [Immemor/RaidCore#69]
With the new low layer which interpret carbine combat event, the datachron message on System Daemon could be fixed.

This ticket should be closed if no more bug is present on System Daemon.
The ticket history is in: https://github.com/NielsH/RaidCore/issues/43

**Comment by NielsH** [comment]
OnchatDC worked well for me as I tested it today. Did you want to test it as well before closing it or ok to do so now?

**Comment by Immemor** [comment]
I wasn't sure. As I split the previous ticket in 2.
But, If for u, all is Ok. We can close it.

**Comment by NielsH** [comment]
Yeah, i just killed system daemons 5 minutes ago with  the master. Things were correctly triggered for me! Will close it.
