### ISSUE TITLE
Ohmna Pillars - fix?

### ISSUE THREAD

**Issue by Eikju** [Immemor/RaidCore#7]
Hey there :)

So there is a problem with Ohmna (we tried it first time). So if a pillar of ohmna is down and you come to the phase in which the lowest pillar will be attacked next, automatically the down pillar with 0 % will be selected.

So maybe you have a function on which the down pillars won't be checked if they are the lowest?

Thank you :)

**Comment by NielsH** [comment]
You're not supposed to let the pillars get to 0% :p 

This might be a fun one for @Wobel - I'm not really able to get into an ohmna fight that has pillars to go 0% at this point. You'd probably have to make a check here https://github.com/NielsH/RaidCore/blob/master/Modules/Ohmna.lua#L37 to check that v > 0 before it assigns it as the lowest

**Comment by Gil-B** [comment]
I'll give it a shot, although our wipes tend to be on other parts of the
fight :P

**Comment by Eikju** [comment]
It is not a question if someone wipes on A or B guys. It is a question of "What if A or B happens?". And If one pillar goes down, the addon won't work correctly anymore :)

**Comment by Gil-B** [comment]
Obviously. But to test the fix we need to trigger the issue, which is
sometimes hard in raids as it depends on 19 other people :)

Anyway, I'll sort it out in a bit.

**Comment by Eikju** [comment]
Our guild is new on Ohmna so sometimes it happens that a pillar goes down :D

**Comment by Gil-B** [comment]
Right, I have a version that should work but I'm not going to be able to
test it this week as I'm not available on our Ohmna night.

You mind giving it a shot, Eikju?
I'll send it to you when I get home.

**Comment by Eikju** [comment]
In this week (saturday and sonday) we also can not test it until thursday. That is our Ohmna-Day :D

**Comment by Gil-B** [comment]
Ah well, no rush :) will try to test it myself after the reset or poke you
if that seems unlikely to happen.

**Comment by Eikju** [comment]
Okay :)

**Comment by Gil-B** [comment]
Hey Eikju,
Can you try this version of the Ohmna module? 
https://gist.github.com/Wobel/26032e7e947f617d0a9d

You just need to replace %APPDATA%\NCSOFT\Wildstar\Addons\RaidCore\Modules\Ohmna.lua with this version :) 
Let me know if it works for you.

**Comment by Eikju** [comment]
Okay. I will test it out for you :)

Thx for the fix!

**Comment by Eikju** [comment]
Hey @Wobel . It works like intended and can be implemented in the release-file :)

**Comment by Gil-B** [comment]
Awesome, thanks.
I'll send a pull request

**Comment by NielsH** [comment]
Fixed in https://github.com/NielsH/RaidCore/commit/ee50013cf21af9d278961a24997e5586af6a6494 :+1:
