### ISSUE TITLE
New start encounter mechanism

### ISSUE THREAD

**Issue by Immemor** [Immemor/RaidCore#70]
Today, each encounter must say when RaidCore must start to catch combat event, trough two lines:

``` lua
mod:RegisterEnableMob("a", "b", "c")
```

``` lua
mod:Start()
```

Instead to have each encounter which should says when to start, the Start/Stop should be managed at a lower layer.

The idea is to:
- Enable the encounter which match with trigger list on "UnitEnteringCombat" event.
- **Start** when the Player entering in combat ,
- **Stop** when the Group is out of combat.

This new mechanism will fix the bug which is: "The encounter don't start after a /reloadui"

**Note:**
 Be careful, every body entering in combat in same time! Players as foes.
 So foes can entering combat before the player.

**Comment by Immemor** [comment]
Ok, I finished a first version, I did some test near capital on basic mobs.

I will try it on Datascape this thursday night (in few hours), I keep you informed.

**Comment by NielsH** [comment]
Cool, I'm especially interested in how well it performs on elemental pairs
:)

**Comment by Immemor** [comment]
That works perfectly in French/English in Elemental Pair Air/Water.

I continu to test.

**Comment by Immemor** [comment]
Well, I kill for the first time this pair, but unfortunately, I didn't test another encounter.

But I'm quite confident.

**Comment by NielsH** [comment]
Testing this now in GA. Worked well the first pull of X89, but no longer works after the first wipe. 

Points to note:   
- We have a stalker scientist stealthing to the boss, this means when we get close to mobs we sometimes switch between enteredcombat states while not actually engaging. Every time this happened I got the "Module ExperimentX89 Loaded"  
- Even after x89 was dead, for example kuralak, and even on second wing (after teleporter) every time we switched combat I got the same debug message, also kuralak never activated/loaded at all.

Doing a reloadui at this point - I do have rclogs to attach later for these 2 bosses.

**Comment by Immemor** [comment]
hum, the wipe timer come too lately maybe, where did stored the logs ?

**Comment by Immemor** [comment]
hum, strange, if players are in combat by a stalker in invisible mode near the boss, that shouldn't Enable the encounter. As the boss itself is not in combat.

really strange. I will look that with your data.

**Comment by NielsH** [comment]
X89: https://docs.google.com/spreadsheets/d/1m-xrEOEu44cnFN8a4U0Mi9NwCdzuO_AQc6tHsA05jtc/edit?usp=sharing

It seems the kuralak log didn't save properly, meh, but we got x89 at least.

**Comment by Immemor** [comment]
You can access to log after Wipe Event, at this moment RaidCore switch on a new buffer.

And from this moment, you can collect log a any moment, until the next wipe event.

**Comment by NielsH** [comment]
Here is one from an encounter that triggered protypes to be loaded while it wasn't needed. This specific one when we did some trash in front of phage maw.
https://docs.google.com/spreadsheets/d/1e0ziipnrs17iGK9slXFaCIKXBLwirGDME25v3jSa8rU/edit?usp=sharing

**Comment by Immemor** [comment]
I didn't filter Boss with InCombat= false, maybe it's that.

Otherwise, from your log, The "Elder Phageborn Vilecaster" have started the Prototype encounter, with is strange.

**Comment by NielsH** [comment]
Well, to clarify, the only thing that is happening is that the module is
being loaded - so it looks like this in chat:
https://i.imgur.com/ZLRqML5.jpg

The module isn't being started at all at any point during all that. So no
bars and such being displayed, just the chat debug message.

**Comment by NielsH** [comment]
Having a look at: https://github.com/NielsH/RaidCore/commit/e1664fafc53a21a96afa1e2f9d69bbba9a4117b6

Initially, `_tCurrentEncounter` is assigned (default: nil) here: https://github.com/NielsH/RaidCore/commit/e1664fafc53a21a96afa1e2f9d69bbba9a4117b6#diff-fb34fdb831a0474a150632a4f8498208R260 when we engage combat

When combat ends, it is disabled here: https://github.com/NielsH/RaidCore/commit/e1664fafc53a21a96afa1e2f9d69bbba9a4117b6#diff-fb34fdb831a0474a150632a4f8498208R1281 - but not assigned to nil again.

So when this happens: https://github.com/NielsH/RaidCore/commit/e1664fafc53a21a96afa1e2f9d69bbba9a4117b6#diff-fb34fdb831a0474a150632a4f8498208R1305
doesn't it trigger on L1314 and re-enable the boss module?

Or maybe I'm reading it wrong, didn't look very detailed in it..

**Comment by Immemor** [comment]
You right, _tCurrentEncounter should be nil again, on WipeEvent.

**Comment by Immemor** [comment]
I don't play tonight, could try to assign `nil` just after `Disable` call.

https://github.com/NielsH/RaidCore/commit/e1664fafc53a21a96afa1e2f9d69bbba9a4117b6#diff-fb34fdb831a0474a150632a4f8498208R1281

**Comment by NielsH** [comment]
We already cleared it sadly. Can confirm though Ohmna activates nicely :) - Though forgot to check for pillars, meh.. 

We might do PTR still this week so will try there if we do.

**Comment by NielsH** [comment]
One thing I saw while solo testing on PTR with this build - a lua error for https://github.com/NielsH/RaidCore/blob/352d6a14a50370e7740f7968562bb12b432df64d/RaidCore.lua#L272 - where `tUnit` was a nil value. This happened when engaging an elemental pair (Aileron/Hydroflux) though the module itself did appear to activate correctly!

Maelstrom/Gloomclaw OnChatDC seemed to work as well.

**Comment by Immemor** [comment]
Hum, Ok

**Comment by Immemor** [comment]
I will manage the unit Out of Combat, I didn't thing to that events which come after the wipe detection.

Otherwise, you have discovered how an error is raised to the interface. ^^, It's not a LUA error popup.
