### ISSUE TITLE
Add a test button in API

### ISSUE THREAD

**Issue by Immemor** [Immemor/RaidCore#72]
Add a test button in the RaidCore Interface.

On the click, that should start:
- Some fake timers,
- Add the player itself as watched unit, 
- Start some fake message
- Draw some pictures,
- etc ...

That will give the possibility to the user to see the rendering of RaidCore in action.
This feature was present on Raiderino, and on DruseraBossMods too.

**Comment by NielsH** [comment]
I can do this once the upcoming release is done. It's not very hard, and we already have this functionality partially (`/raidc bar`, `/raidc unit`), but I just need to make sure it actually renders the bars because outside of raid instances the addon is normally disabled and won't update the bars.

**Comment by Immemor** [comment]
I have an idea for that. I will bring my start/stop service which I did on DruseraBossMods.

**Comment by NielsH** [comment]
Yeah, I think it's very doable. Just need to make sure not to disable/stop it after testing bars if we are already in a raid. Which can be checked through the `monitoring` variable in RaidCore.lua I think.

**Comment by Immemor** [comment]
My idea is to set to true a boolean flag when you request a bar, and on update timer, if no bar is remaining, this flag is set to false.

Like that, Bar service is not link with encounter start/stop.

If during your fight you have no bar, the bar timer is off (as no bar to update). That will save some CPU like that.
