### ISSUE TITLE
SystemDaemon is not enable in french

### ISSUE THREAD

**Issue by Immemor** [Immemor/RaidCore#74]
SystemDaemon Is not enable in french.

I took log and name of SubZone.

Log is saved here: https://docs.google.com/spreadsheets/d/17MY1aoLPQ9HPUc0m_gio57MVgXDdDYUjQZTC0ku4KRg/edit#gid=277832702

![SubZones string](http://img15.hostingpics.net/pics/308008SDSubZones.png)

**Comment by Immemor** [comment]
arf,

"Defeat the System Daemons" is not translated...
Well, this issue will be fixed with https://github.com/NielsH/RaidCore/issues/70

RestrictEventObjective is useless...

**Comment by NielsH** [comment]
For now - it is not useless. It's intended so it only activates the module when the boss is actually active, and not if the boss is dead. It works together with the restrictsubzone/enablesubzone.

Before it would be an issue where the module would be active when we were doing probes for example and we weren't in the system daemons room.

**Comment by Immemor** [comment]
EnteringCombat with IsCombat = true is enough.

**Comment by NielsH** [comment]
Yes, but that would be in https://github.com/NielsH/RaidCore/issues/70 - though until that point, it's good to have it in :)

**Comment by Immemor** [comment]
I started this issu. I will have finish quickly.

**Comment by Immemor** [comment]
Well, with v2.0, this bug is still true. That should come from a string with a 'NO_BREAK_SPACE', I think so.

But I miss my click to retrieve log.
