### ISSUE TITLE
bug: Maelstrom

### ISSUE THREAD

**Issue by Immemor** [Immemor/RaidCore#75]
Problem on load/unload.

https://github.com/NielsH/RaidCore/issues/73

**Comment by Immemor** [comment]
From my point of view. The trigger name is not the good one.

``` lua
local mod = core:NewEncounter("Maelstrom", 52, 98, 120)
if not mod then return end

mod:RegisterEnableMob("Weather Control Station")
```

That shouldn't be "Weather Control Station", but more "Avatus Hologram". 

Or "Maelstrom Authority" itself. In this last case, you lost the timer which announce the start of fight, that's not a big lost.

**Comment by NielsH** [comment]
This might be a good thing to change - but it shouldn't be the cause of the issue, since I am certain it has worked before, and we didn't change the trigger name recently.

I'm gonna see if I can figure out what's causing this on PTR this week.

**Comment by Immemor** [comment]
Many things can drive to this issue:
- "Weather Control Station" is an entry which is not translated ( that will block other language)
- The unitCreated is raised only once by fight, because I have a filter in CombatInterface.
  
  That means, maybe the Core was working with the second, third or more call of unitCreated.
  As this last was also raised when the player change of target.

**Comment by NielsH** [comment]
This appears to be fixed now. Did you still notice anything weird? Otherwise it can be closed.

**Comment by Immemor** [comment]
I didn't fight maelstrom this week, and you ?

**Comment by NielsH** [comment]
Not personally, but I do get feedback from the raid/guild, I asked them if maelstrom worked, and they said yes. They did notice the issues with other bosses. (Ohma/Gloomclaw/avatus/system daemons)

**Comment by Immemor** [comment]
Ok, let's close it so.
