### ISSUE TITLE
EpLogicEarth improvement

### ISSUE THREAD

**Issue by Immemor** [Immemor/RaidCore#80]
On EpLogicEarth, few players ask me to draw a line between the snake on his target.

Obviously the snake's target could be:
- The player with the debuff.
- A block of earth.

Apparently, It take always shortest path between both.

**Comment by NielsH** [comment]
Drawing a line is easy, but I believe the issue with the snake is that every snake "block" is a separate unit. We might be able to look at the snake block that is created first and use that as a starting position to draw the line from/to, but I'm not sure how reliable that is.

**Comment by ghost** [comment]
For Info : If there is a block on the map, the snake will ever focus it instead of the targeted player
