### ISSUE TITLE
RaidCore Version

### ISSUE THREAD

**Issue by Immemor** [Immemor/RaidCore#81]
The user should be able to tell us with version is used on his game. For that the RaidCore Version should be printed somewhere in his interface.

I thinking to add it in the footer area, like:

```
+---------------------------------------------------+
|                     RaidCore                      |
+---------------------------------------------------+
|                                                   |
|                                                   |
|                                                   |
|                                                   |
+---------------------------------------------------+
|   Version: X.Y     Authors: ...             Close |
+---------------------------------------------------+
```

**Comment by NielsH** [comment]
We can do this, but the Authors part could get a bit cluttered. I'm sure there are multiple people that would appreciate being on that list, even if it is for minor contributions.

So I would like to suggest a separate button in the menubar on the left side (below General and Datascape settings) called About - and have this information there, together with a list of authors/developers and contributers.

**Comment by Immemor** [comment]
It's fine for me.

**Comment by Immemor** [comment]
Done in 3.7-alpha
