### ISSUE TITLE
Alpha replacements

### ISSUE THREAD

**Issue by Immemor** [Immemor/RaidCore#88]
``` lua
--@alpha@
local mod = core:NewEncounter("GalerasTest", 6, 0, 16)
--@end-alpha@
```

Obviously, the packaging doesn't work completely. Code surrounded by special keywords is not put in comment in curse version 1.1 or 1.2.

Ref: http://wildstar.curseforge.com/docs/packaging

Something should miss somewhere.

**Comment by NielsH** [comment]
I have spoken about this with someone from Curse who verified the issue. He said he made a ticket for the devs at Curse.

So for now this seems to be something on their side. I'll update if I get a response from them.

**Comment by Immemor** [comment]
did u have any news from them ?

**Comment by NielsH** [comment]
Nothing yet, I'll give them a poke to ask for an update...

**Comment by Immemor** [comment]
Could you add me in the loop with curse ?

**Comment by NielsH** [comment]
The last I heard was:
Torhal │ I'm hoping to get to look at it soon; I'm pretty sure I'll be the one working on it. Other things need doing first, though, unfortunately. 

I'm asking him via IRC on the #wildstaruidev channel on the Freenode network. It's not a very active channel, but it has some addon devs around, some curse guys around and also someone from Carbine.

**Comment by Immemor** [comment]
Ok, the first time, where do you find the log about exportation failed ?

because I can't export 3.2-alpha. I don't known why.

**Comment by Immemor** [comment]
I will copy it manually in curse this time.
