### ISSUE TITLE
bug: /raidc break doesn't work

### ISSUE THREAD

**Issue by adamjedlicka** [Immemor/RaidCore#89]
I have newest version from curse (1.2) and timer is stuck at max time and message about break doesn't disappear.

**Comment by NielsH** [comment]
Hey,

In what zone were you when this happened? I believe it is an issue if you were outside of a recognized raid zone (aka: outside of DS/GA). However if you are inside of those zones, it should work.

So just to confirm if this is the same issue - or something else, could you let me know what zone you were in when it happened?

Thanks!

**Comment by Immemor** [comment]
strange, I'm adding CoreY83, I don't meet any big problem.
More information is needed.

**Comment by adamjedlicka** [comment]
It was in DS and it happened multiple times. Also it wasn't only me because after someone used it a lot of ppl in raid started complaining about it.

**Comment by Immemor** [comment]
Hum,

I'm thinking to your description, I maybe found something.
https://github.com/NielsH/RaidCore/blob/master/RaidCore.lua#L1355

The "RAID_WIPE" event is send after the encounter disable. That probably the bug.

Is bars which are stuck are at the end of an encounter ?

**Comment by Immemor** [comment]
tomorrow, obviously I'm not selected to raid, NieslH will probably raid.

**Comment by adamjedlicka** [comment]
Stack was only BREAK timer and BREAK message. Everything else works perfectly

**Comment by Immemor** [comment]
Oh sorry, I just understand what you are said.

In fact, you speak about a command line.

I known why that doesn't work. **HUD update** is not enable outside a combat now.
I will try to provide a quick fix, and later a better implementation for cpu/memory usage.
